var res = {
	jsonScene : 'src/tools/SoundScene.json',
    example_ColorBars_vsh : "res/openGL/example_ColorBars.vsh",
	example_ColorBars_fsh : "res/openGL/example_ColorBars.fsh",
	showcard_Gothic_fnt : "res/Showcard_Gothic_0.fnt",
    showcard_Gothic_png : "res/Showcard_Gothic.png",
	helloBG_png : "res/helloBG.png",
    start_n_png : "res/start_n.png",
    start_s_png : "res/start_s.png",
	levelCastle_png : "res/castle.png",
	levelMutant_png : "res/mutant.png",
	levelWINTER_png : "res/0_0.png",//"res/levelWINTER.png",
    levelWINTER_ground_png : "res/0_0_ground.png",//"res/levelWINTER_ground.png",
	charBig_png  : "res/charBig.png",
    charBig_plist : "res/charBig.plist",
    background_map00_tmx : "res/background_map00.tmx",
	before_front_map00_tmx : "res/before_front_map00.tmx",
	front_map00_tmx : "res/front_map00.tmx",
	map00_tmx : "res/map00.tmx",
    map01_tmx : "res/map01.tmx",  
	map02_tmx : "res/map02.tmx",
    map03_tmx : "res/map03.tmx", 
	map10_tmx : "res/map10.tmx",
    map11_tmx : "res/map11.tmx",  
	map12_tmx : "res/map12.tmx",
    map13_tmx : "res/map13.tmx",
	map20_tmx : "res/map20.tmx",
    map21_tmx : "res/map21.tmx",  
	map22_tmx : "res/map22.tmx",
    map23_tmx : "res/map23.tmx",
    restart_n_png : "res/restart_n.png",
    restart_s_png : "res/restart_s.png",
    //background_mp3 : "res/background.mp3",
	background_ogg : "res/background.ogg",
    jump_mp3 : "res/jump.mp3",
    pickup_coin_mp3 : "res/pickup_coin.mp3",
	particle_png : "res/particle.png",
	particle_star_png : "res/particle_star.png",
	boss0_json : "res/skeleton/boss0/boss0.ExportJson",
	boss0_plist : "res/skeleton/boss0/boss00.plist",
	boss0_png : "res/skeleton/boss0/boss00.png",
	wind_plist : "res/particles/wind.plist",
	wind_png : "res/particles/wind.png",	
	wind0 : "res/wind0.png",
	wind1 : "res/wind1.png",
	tree0 : "res/tree0.png",
	tree1 : "res/tree1.png",
	sculls_plist : "res/particles/Sculls.plist",
	sculls_png : "res/particles/scull.png",
	sunExplosion_plist : "res/particles/SunExplosion.plist",
	flubber_plist : "res/particles/Flubber.plist",
	sunExplosion_png : "res/particles/point.png",
	charMonsters_png : "res/charMonsters.png",
	//charNaked_png : "res/naked.png",
	cristall_bg_png : "res/cristall_bg.png",
	cristall_png : "res/cristall.png",
	
	//SOUNDS
	
	playMenuBgMusic:"res/sounds/background.mp3", 
    playGameBgMusic:"res/sounds/sfx/level_clear2.mp3", 
	playGameBgLoseMusic:"res/sounds/sfx/level_clear2.mp3", 
	playGameBgWinMusic:"res/sounds/sfx/level_clear2.mp3", 
    playFire1:"res/sounds/sfx/fire1.mp3",
	playFire2:"res/sounds/sfx/fire2.ogg", 
	playFire3:"res/sounds/sfx/fire3.mp3", 
    playRocketStart:"res/sounds/sfx/rocketStart.ogg", 
	playRocketEnd:"res/sounds/sfx/rocketEnd.ogg",
    playButton:"res/sounds/sfx/button_sound.mp3", 
	playPowChage:"res/sounds/sfx/playPowChage.ogg",
	playPlayerJump:"res/sounds/sfx/monster_jump.mp3", 
	playPlayerStaminaError:"res/sounds/sfx/playPlayerStaminaError.ogg",
	playPlayerGunHeat:"res/sounds/sfx/gunHeat.ogg", 
    playPlayerHit: "res/sounds/sfx/playerHit.mp3",  
	playPlayerDie: "res/sounds/sfx/playerDie.mp3",  
	playPlayerFall: "res/sounds/sfx/playPlayerFall.mp3",  
	playBombDie: "res/sounds/sfx/playBombDie.ogg",  
	playBomberFire: "res/sounds/sfx/playBomberFire.ogg",  
	playBomberDie: "res/sounds/sfx/playBomberDie.ogg",  
	playBomberBombFelt: "res/sounds/sfx/bomber_bomb_felt.ogg",  
	playBallDie: "res/sounds/sfx/playBallDie.ogg",  
	playBallFire: "res/sounds/sfx/playBallFire.ogg",  
	playBallHit: "res/sounds/sfx/playBallHit.ogg",  
	playCharBigDie: "res/sounds/sfx/charBigDie.mp3",  
	playCharBigHit: "res/sounds/sfx/charBigHit.mp3",  
	playChickHit: "res/sounds/sfx/chickHit.mp3",  
	playChickDie: "res/sounds/sfx/chickDie.mp3",  
	playChildDie: "res/sounds/sfx/playChildDie.mp3",  
	playChildBite: "res/sounds/sfx/playChildBite.ogg",  
	playCristallPick: "res/sounds/sfx/playCristallPick.ogg",  
	playEagleDie: "res/sounds/sfx/eagleDie.mp3",  
	playEagleHit: "res/sounds/sfx/eagleHit.mp3",  
	playHatDie: "res/sounds/sfx/hatDie.mp3",  
	playHatHit: "res/sounds/sfx/hatHit.mp3",  
	playLazerDie: "res/sounds/sfx/playLazerDie.ogg",  
	playLazerHit: "res/sounds/sfx/playLazerHit.ogg",  
	playLazerFire: "res/sounds/sfx/playLazerFire.ogg",  
	playPinkDie: "res/sounds/sfx/pinkDie.mp3",  
	playPinkHit: "res/sounds/sfx/pinkHit.mp3",  
	playWhiteDie: "res/sounds/sfx/playWhiteDie.ogg",
	playWhiteHit: "res/sounds/sfx/playWhiteHit.ogg",	
	playZombyDie: "res/sounds/sfx/playZombyDie.ogg", 
	playZombyHit: "res/sounds/sfx/playZombyHit.ogg", 	
	playZombyBite: "res/sounds/sfx/playZombyBite.ogg",  
	playIceBroke: "res/sounds/sfx/playIceBroke.mp3",  
	playFireRock: "res/sounds/sfx/fireRock.mp3",  
    playHurt: "res/sounds/sfx/level_clear2.mp3",  
    playLose: "res/sounds/sfx/level_clear2.mp3"
	
};

var g_resources = [
	//SOUNDS
	res.playMenuBgMusic,
    res.playGameBgMusic,
	res.playGameBgLoseMusic,
	res.playGameBgWinMusic,
    res.playFire1,
	res.playFire2,
	res.playFire3,
    res.playRocketStart,
	res.playRocketEnd,
    res.playButton,
	res.playPowChage,
	res.playPlayerJump, 
	res.playPlayerStaminaError,
	res.playPlayerGunHeat, 
    res.playPlayerHit,
	res.playPlayerFall,  
	res.playPlayerDie,  
	res.playBombDie,  
	res.playBomberBombFelt,  
	res.playBomberFire,  
	res.playBomberDie,  
	res.playBallDie,  
	res.playBallFire, 
	res.playBallHit,  
	res.playCharBigDie,  
	res.playCharBigHit,  
	res.playChickHit,  
	res.playChickDie,  
	res.playChildDie,  
	res.playChildBite,  
	res.playCristallPick,  
	res.playEagleDie,  
	res.playEagleHit,  
	res.playHatDie,  
	res.playHatHit,  
	res.playLazerDie,  
	res.playLazerFire,
	res.playLazerHit,  	
	res.playPinkDie,  
	res.playPinkHit,  
	res.playWhiteDie,  
	res.playWhiteHit,  
	res.playZombyDie,  
	res.playZombyHit,  
	res.playZombyBite,  
	res.playIceBroke,  
	res.playFireRock,  
    res.playHurt,  
    res.playLose,
    //image
	res.jsonScene,
	res.background_map00_tmx,
	res.before_front_map00_tmx,
	res.front_map00_tmx,
	res.example_ColorBars_vsh,
	res.example_ColorBars_fsh,
	res.flubber_plist,
	res.sunExplosion_plist,
	res.sunExplosion_png,
	res.sculls_plist,
	res.sculls_png,
	res.wind_plist,
	res.wind_png,	
	res.wind1,
	res.tree0,
	res.tree1,
	res.wind0,
	res.showcard_Gothic_fnt,
    res.showcard_Gothic_png,
	res.levelCastle_png,
	res.levelMutant_png,
	res.levelWINTER_png,
    res.levelWINTER_ground_png,
    res.helloBG_png,
    res.start_n_png,
    res.start_s_png,
	res.charBig_png,
    res.charBig_plist,
    res.map00_tmx,
    res.map01_tmx, 
	res.map02_tmx,
    res.map03_tmx,
	res.map10_tmx,
    res.map11_tmx, 
	res.map12_tmx,
    res.map13_tmx,
	res.map20_tmx,
    res.map21_tmx, 
	res.map22_tmx,
    res.map23_tmx,
    res.restart_n_png,
    res.restart_s_png,
    //res.background_mp3,
    res.jump_mp3,
    res.pickup_coin_mp3,
	res.particle_png,
	res.boss0_json,
	res.boss0_plist,
	res.boss0_png,
	res.charMonsters_png,
	res.cristall_bg_png,
	res.cristall_png
];